# _config.yml
title: "Python Finance Portfolio"
email: your.email@example.com
description: >
  A showcase of my quantitative finance, risk modeling, and Python data analysis projects.
baseurl: "" # leave empty unless you use a subpath
url: "https://sh4r-KO.github.io" # change to your GitHub Pages URL or custom domain

author:
  name: "Aguirre Cabrol"
  email: your.email@example.com
  github: your-username
  linkedin: your-linkedin
  twitter: your-handle

# Build settings
markdown: kramdown
remote_theme: hydecorp/hydejack
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation (sidebar / menu)
menu:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /compound_interest.html


# Hydejack theme options
hydejack:
  dark_mode: true
  accent_color: "#0074D9" # Finance-blue accent
  copyright: "© 2025 Aguirre Cabrol"
  date_format: "%B %d, %Y"

# Collections for projects
collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
